[server]
enableStaticServing = true
enableXsrfProtection = false
enableCORS = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#007580"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[runner]
# Enable this to force installation of packages from requirements.txt
fastRebuildOnFileChange = true

[logger]
level = "info"

[client]
toolbarMode = "minimal"

[deprecation]
showPyplotGlobalUse = false
